# Generated by Django 3.2.3 on 2021-06-07 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_of_car', models.CharField(max_length=64)),
                ('car_model', models.CharField(default='', max_length=64)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.IntegerField(default=0)),
                ('production_year', models.SmallIntegerField(default=0)),
                ('mileage', models.IntegerField(default=0)),
                ('engine_capacity', models.FloatField(default=0.0)),
                ('horse_power', models.IntegerField(default=0)),
                ('country', models.CharField(default='', max_length=64)),
                ('car_color', models.CharField(choices=[('BEIGE', 'Beige'), ('WHITE', 'White'), ('BURGUNDY', 'Burgundy'), ('BROWN', 'Brown'), ('BLACK', 'Black'), ('RED', 'Red'), ('PURPLE', 'Purple'), ('BLUE', 'Blue'), ('SILVER', 'Silver'), ('GRAY', 'Gray'), ('GREEN', 'Green'), ('GOLD', 'Gold'), ('YELLOW', 'Yellow'), ('DIFFERENT', 'Different color')], default='', max_length=32)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('PETROL+LPG', 'Petrol + LPG'), ('PETROL+CNG', 'Petrol + CNG'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], default='', max_length=32)),
                ('type', models.CharField(choices=[('SEDAN', 'Sedan'), ('COUPE', 'Coupe'), ('STATION WAGON', 'Station wagon'), ('HATCHBACK', 'Hatchback'), ('CONVERTIBLE', 'Convertible'), ('SPORT-UTILITY VEHICLE (SUV)', 'SUV'), ('MINIVAN', 'Minivan')], default='', max_length=32)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opinions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nick', to=settings.AUTH_USER_MODEL)),
                ('comment_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='NiceRide.car')),
            ],
        ),
        migrations.CreateModel(
            name='ObserveCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ManyToManyField(to='NiceRide.Car')),
                ('followed_by', models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=128)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaged', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
