# Generated by Django 3.2.3 on 2021-06-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NiceRide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
