# Generated by Django 3.2.3 on 2022-03-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NiceRide', '0005_alter_car_brand_of_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_color',
            field=models.CharField(choices=[('BEIGE', 'Beżowy'), ('WHITE', 'Biały'), ('BURGUNDY', 'Bordowy'), ('BROWN', 'Brązowy'), ('BLACK', 'Czarny'), ('RED', 'Czerwony'), ('PURPLE', 'Fioletowy'), ('BLUE', 'Niebieski'), ('SILVER', 'Srebrny'), ('GRAY', 'Szary'), ('GREEN', 'Zielony'), ('GOLD', 'Złoty'), ('YELLOW', 'Żółty'), ('DIFFERENT', 'Inny kolor')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('PETROL', 'Benzyna'), ('DIESEL', 'Diesel'), ('PETROL+LPG', 'Benzyna + LPG'), ('PETROL+CNG', 'Benzyna + CNG'), ('ELECTRIC', 'Elektryczny'), ('HYBRID', 'Hybrydowy')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='horse_power',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='production_year',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
